### ISSUE TITLE
Code .dsl.factory

### ISSUE THREAD

**Issue by paulvi** [mmnaseri/spring-data-mock#102]
Quick look at `.dsl.factory` give impression of rather complex long hierarchies.

![dslfactory](https://cloud.githubusercontent.com/assets/1614482/16036250/a2818a76-324d-11e6-8fc5-fb21408f909e.png)

Done, using www.objectaid.com plugin

**Comment by paulvi** [comment]
I feel like too many `and` make it complicated.

Instead of

```
    .usingImplementation(SampleImpl1.class)
        .and(SampleImpl2.class)
        .and(SampleImpl3.class)
```

some frameworks use

```
    .usingImplementation(SampleImpl1.class)
    .usingImplementation(SampleImpl2.class)
    .usingImplementation(SampleImpl3.class)
``

style, that is better for commenting out single line.

**Comment by mmnaseri** [comment]
The complexity is inevitable and is not an indication of *unintended coupling*. The classes and interfaces there present a very complex hierarchy that allow for code assistance via IDE when writing expressions through the DSL.

The same complexity is not seen anywhere else in the framework. Think of each class as a non-terminal in a context-free grammar with the start rule being called `Start` (with an eponymous interface) and the ending, terminal rule being called `End` (with an eponymous interface of its own).

There are two DSLs altogether: one to build a repository factory configuration, and another to mock a repository given a configuration (or a preconfigured factory). The first one happens to provide a non-terminal end state that let's you segue from the first to the second, thus seamlessly mocking a repository following a use-once configuration.

**Comment by mmnaseri** [comment]
As for your second comment, that is a matter of taste. Though I do agree that your proposed style makes "commenting out" the opening sequence much easier and more hassle-free, I tend to lean toward an approach that makes the code closer to plain English.

**Comment by paulvi** [comment]
We shared thoughts. Seems no action is needed.

On the second thought, (or is it in fact 3rd):  
How about using varargs

```java
    .usingImplementation(SampleImpl1.class,
        SampleImpl2.class,
        SampleImpl3.class
    )
```

i.e. `usingImplementation(Class... classes )`

That would not however simplify, as pops hassle of converting arrays into list.

And anyways not better enough to change existing API
