### ISSUE TITLE
Add samples outlining configuration scope

### ISSUE THREAD

**Issue by mmnaseri** [mmnaseri/spring-data-mock#105]
As #94 indicates, the current behavior (which let's you customize features for the factory and later override it on a per-repository basis) is not immediately obvious.

There should be samples that elaborate this feature.

**Comment by mmnaseri** [comment]
Added a sample doing just what is described in my latest comment in #94

**Comment by paulvi** [comment]
no sample yet

**Comment by mmnaseri** [comment]
They should be made available in the `development` branch after merging `feature#105`. I have also staged release `1.1.3`. Look at samples around the `PlaneRepository` and `PlaneService`.
