### ISSUE TITLE
spring-data-mock ignore validation

### ISSUE THREAD

**Issue by kopax** [mmnaseri/spring-data-mock#144]
I am using @NotNull for some of my properties in my model.

I have tried to insert in database a model with a null value on this properties and the test succeed.

I was expecting to fail, is it normal, me doing it wrong, not normal, ?

**Comment by mmnaseri** [comment]
Hi,

Can you share a piece of your code? This framework does not do any sort of validation. I might be able to add it without much effort, though, due to the number extension points in the code.

**Comment by kopax** [comment]
After speaking with some spring guys, it appear unit testing is already done and this plugin as non sens.
I argued I needed to test my custom implementation but they recommend to just load the context and do it in a embedded database or locale one.

**Comment by mmnaseri** [comment]
Remember that this framework is targeting a very specific need: **unit testing** the service built on top of Spring Data. Without the use of this program, you will need to start a whole application context.

This will start up all of your components, thus breaking the isolation that is required for unit testing the services. Even if you start writing super-small application context configurations to just contain the specific components that are required to start your service, that will again limit you to having to test your service in the company of all of its dependencies. Which, again, breaks the isolation.

Also, when you are unit testing, you need to be able to test various ways in which your service interacts with your database in hypothetical scenarios, such as when the database fails to respond, it times out, it returns data that is not exactly what you expected it to be, and so on.

As such, this framework is aiming to fill that particular gap. If you find that you don't need it, that is absolutely fine. However, I wrote this out of a personal need, and will continue to maintain it. Do not expect it to replace your database backend for integration tests and such, though.
