### ISSUE TITLE
Probles with ...In requests

### ISSUE THREAD

**Issue by neonomaly** [mmnaseri/spring-data-mock#153]
Hi. Have Spring Data CRUD Repository with method 
`List<Order> findByStatusIn(List<Order.Status> statusList);`
During test execution have this exception:
`Encountered an error while resolving operation metadata: public abstract java.util.List OrderRepository.findByStatusIn(java.util.List)`
And nested exception:
`OrderRepository: Expected parameter 0 on method findByStatusIn to be a descendant of class Order$Status`

**Comment by hitokun-s** [comment]
I encountered the same problem.

**Comment by KatGunz** [comment]
Is there a known work around for this issue?

**Comment by hitokun-s** [comment]
FYI
I solved this problem by creating JpaRepository mocking system in Groovy.  
https://github.com/hitokun-s/mock-jpa-repository-test

**Comment by mmnaseri** [comment]
Hi all,

Sorry for the super late reply. I had to figure out some kinks with open-source contribution policies with my current employer. Now that that is resolved, I'll be back in business.

@neonomaly @hitokun-s @KatGunz this is a result of an oversight on my part. I simply haven't implemented the In operator, it seems. I will have to investigate and fix this.

**Comment by mmnaseri** [comment]
This should be fixed as of #156 by @MateuszStefek
