### ISSUE TITLE
Is this supporting Spring framework 3?

### ISSUE THREAD

**Issue by owlab** [mmnaseri/spring-data-mock#159]

**Comment by hitokun-s** [comment]
FYI
I solved this problem by creating JpaRepository mocking system in Groovy.
https://github.com/hitokun-s/mock-jpa-repository-test

**Comment by mmnaseri** [comment]
Hi @owlab,
This framework supports Spring 3. I actually think that the examples are using 3.

**Comment by mmnaseri** [comment]
@hitokun-s thanks for the comment. I appreciate that I haven't been keeping this repo as up-to-date as I have wanted to. Thanks for contributing!
