### ISSUE TITLE
Add support for `QueryDslPredicateExecutor`

### ISSUE THREAD

**Issue by tsachev** [mmnaseri/spring-data-mock#3]

**Comment by mmnaseri** [comment]
It is planned, and it is fairly easy to add as an extension to the framework itself. Have a look at `com.mmnaseri.utils.spring.data.commons.~` package for samples of implementing Spring data interface methods.

You can see in `com.mmnaseri.utils.spring.data.proxy.impl.DefaultTypeMappingContext` how I am adding these defaults, though you can always add these implementations on a per repository or per project basis.

I would be more than happy to delegate this, as it might not get the attention it deserves with me alone doing it.

**Comment by mmnaseri** [comment]
@tsachev This is now supported in `development`. Can you confirm that the latest version in the `development` branch satisfies your expectations?

If so, I can kickstart the Maven Central release for `v1.1`, so that it is distributed to everyone.

**Comment by mmnaseri** [comment]
I think at this point the regression tests should be enough assume the feature works. I am going to close this ticket and open another one if any issues arise that result from malfunction in this feature.
