### ISSUE TITLE
Add VersionEye maven plugin

### ISSUE THREAD

**Issue by mmnaseri** [mmnaseri/spring-data-mock#52]
This will let us get more reliable dependency version info when a build is made

**Comment by mmnaseri** [comment]
Labelling as `invalid` and closing as the current version of the plugin (`3.9.2`) requires an older version of Maven (3.1).

**Comment by paulvi** [comment]
OK, this is why  dependency version info is not visible

**Comment by mmnaseri** [comment]
Yeah. I will have to do this manually for now (reimport the project into VersionEye every time I make a change to `development`) and open a ticket with them.
