### ISSUE TITLE
To give note about `commons-logging` dependency?

### ISSUE THREAD

**Issue by paulvi** [mmnaseri/spring-data-mock#54]
```
		<dependency>
		    <groupId>com.mmnaseri.utils</groupId>
		    <artifactId>spring-data-mock</artifactId>
		    <version>1.0.3</version>
		    <scope>test</scope>
		    <exclusions>
		    	<exclusion>
		    		<artifactId>commons-logging</artifactId>
		    		<groupId>commons-logging</groupId>
		    	</exclusion>
		    </exclusions>
		</dependency>
	</dependencies>
```

or with maven-enforcer-plugin config as below, build of cause fails over `commons-logging` dependency

```
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>1.3.1</version>
				<executions>
					<execution>
						<id>enforce-version</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration><!-- as in spring-boot-starters pom -->
							<rules>
								<bannedDependencies>
									<excludes>
										<!-- exclude all log4j:log4j, commons-logging -->									
										<exclude>log4j:log4j:[0.0,9)</exclude>
										<exclude>commons-logging:*:*</exclude>
									</excludes>
									<searchTransitive>true</searchTransitive>
								</bannedDependencies>
							</rules>
							<fail>true</fail>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
```

**Comment by mmnaseri** [comment]
Do you mean to say that having commons logging as a dependency breaks your build?

**Comment by mmnaseri** [comment]
@paulvi Do you mean to say that having commons logging as a dependency breaks your build?

**Comment by mmnaseri** [comment]
I can't remove the logging dependency, since I am logging a bunch of stuff to the output at various phases. I think `exclude`ing the dependency whenever it clashes with your project is the best approach.

I might think of a way to decouple logging entirely so that there is an optional logging module (maybe by introducing a logging interface that doesn't do anything by default and is implemented using `commons-logging` in a separate module that you can explicitly add to your project).

I will think on this some more.

**Comment by paulvi** [comment]
I guess note in READE or wiki would be enough.

**Comment by mmnaseri** [comment]
Sure. I will do that. And then I will open a story to decouple logging, since I guess most of the time it won't be used, except for debugging purposes.

**Comment by paulvi** [comment]
BTW Spring core also depends on commons-logging, so the solution is similar

**Comment by mmnaseri** [comment]
Done.
