### ISSUE TITLE
Prepare for release `1.1`

### ISSUE THREAD

**Issue by mmnaseri** [mmnaseri/spring-data-mock#60]
At this point I am waiting on responses on #54.
I have closed everything else for milestone 1.1 and will work on #56 which will be the second major feature released with `1.1`.

**Comment by paulvi** [comment]
#54 is absolutely not blocker as the #54 already has documentation solution

**Comment by mmnaseri** [comment]
Thanks for the clarification. I have been kind of lazy about getting `1.1` out the door. I will do that first thing, after I finish #56 (I assume that I can deliver that tomorrow, but I might be overestimating myself here. We will see).

**Comment by mmnaseri** [comment]
Release `v1.1` is pushed to central. It will take about a day for the release to be made available publicly and for central indices to be refreshed.

@paulvi I hope this unblocks you.

**Comment by mmnaseri** [comment]
`1.1` is now officially in central: http://repo1.maven.org/maven2/com/mmnaseri/utils/spring-data-mock/1.1/

**Comment by paulvi** [comment]
OK, trying out

please follow http://semver.org/ for versioning MAJOR.MINOR.PATCH, e.g. 1.1.0, for future releases

**Comment by mmnaseri** [comment]
Sure. Thanks for pushing me to make this project better :)
