### ISSUE TITLE
https://mmnaseri.github.io/spring-data-mock/site/#/roadmap outdated

### ISSUE THREAD

**Issue by paulvi** [mmnaseri/spring-data-mock#67]
https://mmnaseri.github.io/spring-data-mock/site/#/roadmap outdated

Propose just to remove and use README section

**Comment by paulvi** [comment]
Similar for https://mmnaseri.github.io/spring-data-mock/site/#/changelog

**Comment by mmnaseri** [comment]
Yeah, I haven't had the time these past days to move the issues I worked on to do the proper places in the documentation.

**Comment by mmnaseri** [comment]
Updated the documents to reflect the latest state.

**Comment by paulvi** [comment]
Not seen in https://mmnaseri.github.io/spring-data-mock/site/#/changelog

**Comment by mmnaseri** [comment]
That is weird. Let me rebuild the site.

**Comment by mmnaseri** [comment]
Seems to be alright now.
