### ISSUE TITLE
Fix up the dependencies left from hastily adding support for Querydsl

### ISSUE THREAD

**Issue by paulvi** [mmnaseri/spring-data-mock#68]
![1_1](https://cloud.githubusercontent.com/assets/1614482/15983093/fe6f9cfa-2fce-11e6-9d50-d20e4c20a787.PNG)

- [ ] I am confused why there is now slf4j as well. 
As we just settle it down in #54

- [ ] Also possibly querydsl should be optional, and there may be issues about what exact version to use

**Comment by paulvi** [comment]
yep, got warnings

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/Paul%20Verest/.m2/repository/ch/qos/logback/logback-classic/1.1.7/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Paul%20Verest/.m2/repository/org/slf4j/slf4j-log4j12/1.7.21/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```

**Comment by paulvi** [comment]
Important, one can depended on slf4j API, but never on slf4j-log4j (implementation) directly

**Comment by mmnaseri** [comment]
I see. Yeah, my bad. This seems to be because I didn't take enough care when I added the dependency to Querydsl. I will fix this.

**Comment by paulvi** [comment]
Loos OK now: only `commons-logging`
