### ISSUE TITLE
Add samples to the project

### ISSUE THREAD

**Issue by paulvi** [mmnaseri/spring-data-mock#79]
There should be sample JUnits to demo what works (and what yet not)

One of sample can be use case in #78  #69 #54

In other words, some end user oriented examples

**Comment by mmnaseri** [comment]
Yup. That is the aim. That's why I moved project to its own submodule (see #25)

**Comment by paulvi** [comment]
I will do PR for simplest sample.

And it fails for 1.1.1

**Comment by mmnaseri** [comment]
Done, as of 0c2f071

**Comment by paulvi** [comment]
Take a look at https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples for how samples can be organized
