### ISSUE TITLE
Spread the word, give a talk

### ISSUE THREAD

**Issue by paulvi** [mmnaseri/spring-data-mock#85]
Currently I can't recommend this project as if fails from start on simplest cases #83 #84 

However over time it will be fine, and good shape for new users.

Then would you give a (remote) talk for Shenzhen Java User Group http://szjug.github.io/ ?
I guess Spring Boot themed meeting would be great fit.

**Comment by mmnaseri** [comment]
I do not think it fails for no reason. I have found that the reason the sample you have introduced doesn't work is 1) Maven artifact version conflict and 2) lack of custom implementation.

I would be more than honored to do that :) Thank you for the kind offer.

**Comment by paulvi** [comment]
Once we decide on date, should be within 2-4 month.

**Comment by mmnaseri** [comment]
Closing, as I think the discussion should be followed in szjug/szjug.github.io/issues/20
