### ISSUE TITLE
Style for pom.xml

### ISSUE THREAD

**Issue by paulvi** [mmnaseri/spring-data-mock#92]
Usual standard is to have these section in such order

```xml
<properties>

<dependencies>

<build>
```

Currently it is reverse order.

**Comment by mmnaseri** [comment]
Thanks for the note. I will fix this.

**Comment by mmnaseri** [comment]
Going to adopt http://maven.apache.org/developers/conventions/code.html#POM_Code_Convention (which boils down to the ordering mentioned above by @paulvi)

**Comment by paulvi** [comment]
Good to recall about http://maven.apache.org/developers/conventions/code.html#POM_Code_Convention too.
Now I am just looking at Spring Boot pom's as example.
