### ISSUE TITLE
Allow for specifying a fallback key generator on a per-application basis

### ISSUE THREAD

**Issue by paulvi** [mmnaseri/spring-data-mock#93]
As started in https://github.com/mmnaseri/spring-data-mock/issues/84#issuecomment-225470026

> makes the assumption that ID generation starts at 1L

```java
        final CustomerRepository repository = RepositoryFactoryBuilder.builder()
                .mock(CustomerRepository.class);
        repository.save(new Customer());

        Customer c = repository.findOne(1L);
```

I would prefer to specify that Hibernate is used, and have default to start from 1.
And possibly more.

Please leave this open for other people to comment.

**Comment by mmnaseri** [comment]
This is possible by using `SequentialLongKeyGenerator` as your key generator when mocking the interface:

    final CustomerRepository repository = RepositoryFactoryBuilder.builder()
        .generateKeysUsing(SequentialLongKeyGenerator.class)
        .mock(CustomerRepository.class);

**Comment by mmnaseri** [comment]
You can configure a bunch of different things. Here is how: https://mmnaseri.github.io/spring-data-mock/site/#/readme#using-the-dsl-to-create-a-configuration

Is there any other configuration point that you are interested in?

**Comment by paulvi** [comment]
what class to use within `.generateKeysUsing(` to get Hibernate like numbering?

**Comment by paulvi** [comment]
Also

> You have to note that this builder is stateless, meaning that each of the methods in this builder will not modify an internal state, but rather return an object which reflects all the configurations up to this point.

Does it mean that it is impossible to specify  KeyGenerator only one time like 

```java
final RepositoryMockBuilder builder = new RepositoryMockBuilder();
    builder.generateKeysUsing(UUIDKeyGenerator.class) //***

final UserRepository repository = builder.mock(UserRepository.class);
```

**Comment by mmnaseri** [comment]
Yes. The key generator is something you specify right when you are about to mock the repository, since keys are bound to entities. It is possible to redesign this process so that there is a key generation strategy defined as a default at the repository factory configuration level, which would mean that you could set a default fallback per application, rather than per repository.

**Comment by mmnaseri** [comment]
Are you requesting the following feature?

> Allow for specifying a fallback key generator on a per-application basis

**Comment by paulvi** [comment]
yes, I think those using Hibernate should have ability to specify that only one time.

And it would take care of defaults for at least KeyGenerators.

And personally, I still don't know what KeyGenerators to use to mimic Hibernate.

**Comment by mmnaseri** [comment]
You can use `SequentialLongKeyGenerator` to generate "long" keys starting from `1L`. You can specify defaults for everything else. The only thing that doesn't have a default fallback is the key generation.

**Comment by mmnaseri** [comment]
Using the DSL for repository factory configuration you can now specify a fallback key generator for your repository. So, for instance, to assume a default key generator that would generate keys of type `Long` with an initial value of `1` and a step count of `1`, you can do this:

````java
final RepositoryFactoryConfiguration configuration = builder()
    .withDefaultKeyGenerator(new ConfigurableSequentialLongKeyGenerator(1L, 1L))
    .configure();
````

Now, when mocking via the `RepositoryFactory`, if you specify `null` as the key generator, this key generator will be used instead. So, unless you explicitly say `.withoutGeneratingKeys()` when using the `RepositoryMockBuilder` DSL, you will get the default key generator.

**Comment by mmnaseri** [comment]
there are two methods called `.generateKeysUsing(...)`, one that takes a `Class<? extends KeyGenerator>` and the other takes an instance of `KeyGenerator`.

These two are defined on the RepositoryMockBuilder DSL and configure the key generation for the current mock. The `withDefaultKeyGenerator(...)` method, as the name implies, defines a default that can be used for all repository mocks created using the configuration at hand.

I am going to update the documents, too.
